In [3]:
import numpy as np 

In [5]:
# Creacion de un arreglo a partir de una lista
lista1 = [1,2,3,4,5]
arreglo1 = np.array(lista1)
arreglo1

array([1, 2, 3, 4, 5])

In [7]:
type(arreglo1)

numpy.ndarray

In [9]:
# Creacion de un arreglo a partir de una lista de listas 
lista2 = [[1,2,3],[4,5,6],[7,8,9]]
arreglo2 = np.array(lista2)
arreglo2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Las listas pueden contener diversos tipos de datos 
lista = ["a", True, 1]
lista

['a', True, 1]

In [11]:
# Los arreglos solo pueden tener un mismo tipo de datos 
# usan menos espacion en memoria
arreglo = np.array(lista)
arreglo # solo se almacenarion textos

array(['a', 'True', '1'], dtype='<U11')

In [13]:
# Creacion de arreglos con ceros
arreglo3 = np.zeros((5,4))
arreglo3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
# Creacion de arreglo con numeros aleatorios uniformes entre 0 y 1 
np.random.random((3,2))

array([[0.48258567, 0.58983202],
       [0.23549613, 0.21057174],
       [0.19003539, 0.14287496]])

In [17]:
# Creacion de arreglos en un rango
np.arange(-2,7)

array([-2, -1,  0,  1,  2,  3,  4,  5,  6])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
arreglo1 = np.array([[1,2],[5,7]])
arreglo2 = np.array([[8,9],[5,7]])
arreglo3 = np.array([[1,2],[5,7]])

In [19]:
arreglo_3D = np.array([arreglo1,arreglo2,arreglo3])
arreglo_3D

array([[[1, 2],
        [5, 7]],

       [[8, 9],
        [5, 7]],

       [[1, 2],
        [5, 7]]])

In [21]:
arreglo3 = np.zeros((5,4))
arreglo3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
arreglo3.shape

(5, 4)

In [25]:
# Conversiones de arreglos multidimensional a unidimiensional
lista2 = [[1,2,3],[4,5,6],[7,8,9]]

arreglo2 = np.array(lista2)
arreglo2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arreglo2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# Cambio de dimension de un arreglo 
arreglo = np.array([[1,2],[3,4],[5,6]])
arreglo.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
# ejemplo de error al momento de cmabiar de dimension 
arreglo.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

#### Matrices y Tensores en NumPy

In [36]:
np.array([1.25,2.43,200.88]).dtype

dtype('float64')

In [40]:
arreglo_int = np.array([[1,2,3],[4,5,6]])
arreglo_int.dtype

dtype('int32')

In [42]:
arreglo_string = np.array(["Introduccion","a","la","programacion"])
arreglo_string.dtype

dtype('<U12')

In [48]:
# Uso de dtype como argumento
arreglo = np.array([1.25,2.43,200.88], dtype = np.float32) # Mismo arreglo de arrriba
arreglo.dtype

dtype('float32')

In [52]:
# Cambio de tipo de arreglo 
arreglo_boleano = np.array([[True, False]], dtype = np.bool_)
arreglo_boleano.dtype

dtype('bool')

In [62]:
arreglo = arreglo_boleano.astype(np.int32)
arreglo

array([[1, 0]])

In [64]:
# Homologacion del tipo por jerarquia 
np.array([0,50,50.8]).dtype

dtype('float64')

In [66]:
np.array([False,42])
# Los valores que menos espacio ocupan son los boleanos - enteros - flotantes - cadenas alfanumericas strings 

array([ 0, 42])