In [2]:
import numpy as np

In [4]:
# indexacion de un solo elemento
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Extraccion de elementos de forma ascendente
x[2]

2

In [10]:
# Extraccion de elementos en forma ascendente 
x[-2]

8

In [12]:
# Conversion del arreglo a formato bidimencional
x.shape = (2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
# Extraccion del elmento con indice 1 en renglon e indice 3 en columna 
x[1,3]

8

In [16]:
# Alternativa de extraccion del elemento con indice 1 en renglon e indice 3 en columna 
x[1][3]

8

In [18]:
# Extraccion del elemento con indice 1 en renglon y primer elemento en forma descendente 
x[1,-1]

9

In [20]:
# Extraccion del renglon completo con indice 0 (al no especificar indice de columna)
x[0]

array([0, 1, 2, 3, 4])

In [22]:
# Cortes en arreglos 
x = np.array([0,1,2,3,4,5,6,7,8,9])
x[1:7:2] # Formato "start:stop:step" "inicio - final - pasos"

array([1, 3, 5])

In [24]:
# Corte de arreglo de adelante hacia atras, considerando dos elementos
x[-2:10]

array([8, 9])

In [26]:
# Corte del arreglo de adelante hacia atras, iniciando tres posiciones a partir del final y retrociendiendo 
# hasta tener como limite el numero 3
x[-3:3:-1]

array([7, 6, 5, 4])

In [32]:
# Definicion de un nuevo arreglo 
# Creacion de un arreglo en forma descendiente - Del 10 al 1 (sin incluirlo ) - decrementos 
x = np.arange(10,1,-1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [34]:
# Extraccion de elementos especificos del arreglo 
x[np.array([3,3,1,8])] # Extraccion de elementos con indices 3,3,1,8

array([7, 7, 9, 2])

In [36]:
# Extraccion de elemntos con indices 3,3,-3 (descendente) y 8 
x[np.array([3,3,-3,8])]

array([7, 7, 4, 2])

In [38]:
# Extraccion basada en pares 
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [40]:
# Extraccion de "coordenadas" (0,0), (2,1) y (4,2)
y[np.array([0,2,4]), np.array([0,1,2])]

array([ 0, 15, 30])

#### Union de Arreglos 

In [43]:
# Concatenacion de vectores 
arr = np.concatenate(([1,2,3],[4,5,6]))
arr

array([1, 2, 3, 4, 5, 6])

In [45]:
# Apilado vertical de vectores
np.stack(([1,2,3],[4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
# Concatenacion de matrices 
mat_1 = np.array([[1,2,3],[4,5,6]])
mat_2 =np.array([[1,1,1],[2,2,2]])
np.concatenate((mat_1, mat_2), axis = 0) 

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [51]:
np.concatenate((mat_1, mat_2), axis = 1)

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 2, 2, 2]])

In [53]:
np.concatenate((mat_1, mat_2), axis = None)

array([1, 2, 3, 4, 5, 6, 1, 1, 1, 2, 2, 2])

##### 1. Operaciones básicas con matrices

In [55]:
import numpy as np

# Crear dos matrices

matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matriz2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Sumar y restar matrices

suma = matriz1 + matriz2

resta = matriz1 - matriz2

print("Suma de matrices:")

print(suma)

print("\nResta de matrices:")

print(resta)

Suma de matrices:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Resta de matrices:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


##### 2. Filtrar datos usando máscaras

In [59]:
# Crear un arreglo con datos

datos = np.array([10, 15, 20, 25, 30, 35, 40])

# Filtrar elementos mayores a 20

filtro = datos > 20

datos_filtrados = datos[filtro]

print("Datos originales:", datos)

print("Datos mayores a 20:", datos_filtrados)

Datos originales: [10 15 20 25 30 35 40]
Datos mayores a 20: [25 30 35 40]


##### 3. Normalización de datos en una matriz

In [62]:
# Crear una matriz con datos simulados

matriz = np.random.randint(50, 100, size=(4, 4))

# Normalizar los datos por columna

matriz_normalizada = (matriz - np.min(matriz, axis=0)) / (np.max(matriz, axis=0) - np.min(matriz, axis=0))

print("Matriz original:")

print(matriz)

print("\nMatriz normalizada:")

print(matriz_normalizada)

Matriz original:
[[74 73 79 75]
 [98 57 98 81]
 [84 94 76 52]
 [52 81 81 87]]

Matriz normalizada:
[[0.47826087 0.43243243 0.13636364 0.65714286]
 [1.         0.         1.         0.82857143]
 [0.69565217 1.         0.         0.        ]
 [0.         0.64864865 0.22727273 1.        ]]


##### 4. Generar secuencias y manipulación de forma

In [65]:
# Crear una secuencia de números

arreglo = np.arange(1, 13)

# Reestructurarlo como una matriz de 3x4

matriz = arreglo.reshape(3, 4)

# Transponer la matriz

transpuesta = matriz.T

print("Matriz original:")

print(matriz)

print("\nMatriz transpuesta:")

print(transpuesta)

Matriz original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matriz transpuesta:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


##### 5. Estadísticas descriptivas en una matriz

In [68]:
# Crear una matriz con datos simulados

datos = np.random.randint(1, 101, size=(5, 4)) # 5 estudiantes, 4 materias

# Calcular estadísticas por estudiante y por materia

promedio_por_estudiante = np.mean(datos, axis=1)

promedio_por_materia = np.mean(datos, axis=0)

maximo_por_materia = np.max(datos, axis=0)

print("Matriz de calificaciones:")

print(datos)

print("\nPromedio por estudiante:", promedio_por_estudiante)

print("Promedio por materia:", promedio_por_materia)

print("Máximo por materia:", maximo_por_materia)

Matriz de calificaciones:
[[71 52  4 36]
 [82 95  5 79]
 [74 55 21 11]
 [93 34 13 60]
 [73 66 64 63]]

Promedio por estudiante: [40.75 65.25 40.25 50.   66.5 ]
Promedio por materia: [78.6 60.4 21.4 49.8]
Máximo por materia: [93 95 64 79]


##### 6. Producto punto y multiplicación de matrices

In [71]:
# Crear dos matrices

matriz1 = np.array([[1, 2], [3, 4]])

matriz2 = np.array([[5, 6], [7, 8]])

# Producto elemento a elemento

producto_elemento = matriz1 * matriz2

# Producto punto

producto_punto = np.dot(matriz1, matriz2)

print("Producto elemento a elemento:")

print(producto_elemento)

print("\nProducto punto:")

print(producto_punto)

Producto elemento a elemento:
[[ 5 12]
 [21 32]]

Producto punto:
[[19 22]
 [43 50]]


##### 7. Simular datos de ingresos y analizar rangos

In [74]:
# Crear datos simulados de ingresos mensuales

ingresos = np.random.randint(20000, 80000, size=12)

# Calcular estadísticas

ingreso_promedio = np.mean(ingresos)

ingresos_altos = ingresos[ingresos > 50000]

ingresos_bajos = ingresos[ingresos < 30000]

print("Ingresos mensuales:", ingresos)

print("\nIngreso promedio:", ingreso_promedio)

print("Meses con ingresos altos (> 50,000):", ingresos_altos)

print("Meses con ingresos bajos (< 30,000):", ingresos_bajos)

Ingresos mensuales: [48300 38199 37377 63843 76165 25814 74188 22445 32157 32665 60898 63187]

Ingreso promedio: 47936.5
Meses con ingresos altos (> 50,000): [63843 76165 74188 60898 63187]
Meses con ingresos bajos (< 30,000): [25814 22445]


##### 8. Operaciones avanzadas con álgebra lineal

In [77]:
# Crear una matriz cuadrada

matriz = np.array([[4, 2], [1, 3]])

# Calcular la inversa y el determinante

inversa = np.linalg.inv(matriz)

determinante = np.linalg.det(matriz)

# Verificar si la multiplicación con su inversa produce la matriz identidad

identidad = np.dot(matriz, inversa)

print("Matriz original:")

print(matriz)

print("\nInversa de la matriz:")

print(inversa)

print("\nDeterminante de la matriz:", determinante)

print("\nVerificación (matriz identidad):")

print(identidad)

Matriz original:
[[4 2]
 [1 3]]

Inversa de la matriz:
[[ 0.3 -0.2]
 [-0.1  0.4]]

Determinante de la matriz: 10.000000000000002

Verificación (matriz identidad):
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]
