#### Operaciones con arreglos en Numpy

In [6]:
import numpy as np
accidentes = np.array([[0,1,1],[1,0,1],[1,3,2],[2,2,0]])

In [8]:
# a) El numero total de accidentes durante los cuatro años 
accidentes.sum()

14

In [10]:
# b) el numero total de accidentes por area (por columna)
accid_areas = accidentes.sum(axis=0)
accid_areas

array([4, 6, 4])

In [14]:
print("Los accidenntes del area 1: ", accid_areas[0])
print("Los accidenntes del area 2: ", accid_areas[1])
print("Los accidenntes del area 3: ", accid_areas[2])

Los accidenntes del area 1:  4
Los accidenntes del area 2:  6
Los accidenntes del area 3:  4


In [16]:
# c) el numero total de accidentes por año (por renglon)
accid_anios = accidentes.sum(axis=1)
accid_anios

array([2, 2, 6, 4])

In [28]:
# c) el numero total de accidentes por año (por renglon)
accid_anios = accidentes.sum(axis=1, keepdims=True)
accid_anios

array([[2],
       [2],
       [6],
       [4]])

In [34]:
print("Los accidenntes del año 1: ", accid_anios[0])
print("Los accidenntes del año 2: ", accid_anios[1]) 
print("Los accidenntes del año 3: ", accid_anios[2]) 
print("Los accidenntes del año 4: ", accid_anios[3]) 

Los accidenntes del año 1:  [2]
Los accidenntes del año 2:  [2]
Los accidenntes del año 3:  [6]
Los accidenntes del año 4:  [4]


In [36]:
# El numero maximo y minimo de accidentes por area y año
maximo = accidentes.max()
minimo = accidentes.min()
print(f"Maximo de accidentes: {maximo}")
print(f"Minimo de accidentes: {minimo}")


Maximo de accidentes: 3
Minimo de accidentes: 0


In [38]:
# El numero promedio de accidentes por area 
promedio = accidentes.mean()
print(f"Promedio de accidentes: {promedio}")

Promedio de accidentes: 1.1666666666666667


#### Operaciones Vectorizadas

##### Determine la suma descrita mediante un ciclo en python y una funcion vectorizada de NumPy

In [47]:
# Definimos el arreglo 
arreglo = np.array([[1,2,3],[4,5,6]])
dimensiones = arreglo.shape
print(dimensiones[0]) # Renglones 
print(dimensiones[1]) # Columnas 
print(arreglo[0][0])

2
3
1


In [57]:
# Determine la suma del arreglo mediante un ciclo en Python
import time 
inicio = time.time()

arreglo_final = np.zeros((2,3))
for renglon in range (dimensiones[0]):
    for columna in range(dimensiones[1]):
        arreglo_final[renglon][columna] = arreglo[renglon][columna] + 3 
print(arreglo_final)
fin = time.time()
print("Tiempo total de ejecucion(Segundos.)", fin - inicio)

[[4. 5. 6.]
 [7. 8. 9.]]
Tiempo total de ejecucion(Segundos.) 0.000997304916381836


In [59]:
# determine la suma del arreglo mediante una funcion vectorizada de NumPy
import time 
inicio = time.time()

arreglo_final = arreglo + 3 
print(arreglo_final)
fin = time.time()
print("Tiempo total de ejecucion(Segundos.)", fin - inicio)

[[4 5 6]
 [7 8 9]]
Tiempo total de ejecucion(Segundos.) 0.000997304916381836


#### Broadcasting

##### Adicion de dos arreglos

In [68]:
arreglo1 = np.array([[1,2,3],[4,5,6]])
arreglo2 = np.array([[7,8,9],[10,11,12]])
arreglo3 = arreglo1 + arreglo2
arreglo3

array([[ 8, 10, 12],
       [14, 16, 18]])

##### Evaluacion de condiciones

In [72]:
arreglo1 = np.array([[1,2,3],[4,5,6]])
arreglo1 > 2

array([[False, False,  True],
       [ True,  True,  True]])

##### Funciones que por naturaleza fueron diseñanadas para trabajar de manera unidimensional no vectorial
##### Las Funciones de Python no estan vectorizadas de origen

In [114]:
arreglo = np.array(["NumPy","maneja","vectorizacion"])
len(arreglo) > 5

False

##### Vectorizacion de funciones no vectorizadas de origen

In [116]:
len_vectorizada = np.vectorize(len)
len_vectorizada(arreglo) > 5

array([False,  True,  True])

##### Broadcasting en renglones

In [122]:
arreglo = np.arange(10).reshape((2,5))
arreglo

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [124]:
arreglo + np.array([0,1,2,3,4])

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

##### Broadcasting en columnas

In [131]:
arreglo = np.arange(10).reshape((2,5))
arreglo + np.array([0,1]).reshape((2,1))

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

##### Ejemplo de broadcasting donde la operacion NO es factible

In [134]:
arreglo + np.array([0,1])

ValueError: operands could not be broadcast together with shapes (2,5) (2,) 

##### Voltear un arreglo

In [139]:
arreglo = np.array([[1.1,1.2,1.3],[2.1,2.2,2.3],[4.1,4.2,4.3]])
np.flip(arreglo)

array([[4.3, 4.2, 4.1],
       [2.3, 2.2, 2.1],
       [1.3, 1.2, 1.1]])

##### Transposicion de un arreglo 

In [144]:
arreglo = np.array([[1.1,1.2,1.3],[2.1,2.2,2.3],[4.1,4.2,4.3]])
np.transpose(arreglo)

array([[1.1, 2.1, 4.1],
       [1.2, 2.2, 4.2],
       [1.3, 2.3, 4.3]])

In [146]:
# Operacion 1 
np.array([[1,2],[3,4]]) * np.array([[5],[10]])

array([[ 5, 10],
       [30, 40]])

In [148]:
# Operacion 2
np.array([[1,2],[3,4]]) - np.array([[5,10]])

array([[-4, -8],
       [-2, -6]])

In [ ]:
Que tal buen dia 
el motivo de este correo es para solicitar informacion a cerca de futuras vacantes de soporte de ventas en la sucursal de TLATL.
Me llamo Eliuth Misraim Rojas Villavicencio y Provengo del estado de Tlaxcala pero actualmente me encuentro trabajando en el centro de distribucion en monterrey
quisiera saber si tienen considerado abrir una vacante en dicha sucursal pues actualmente creo que seria una oportunidad que se adapta a mis planes de desarrollo
Actualmente me encuentro trabajando en el area de Movimiento de Materiales pero cuento con un buen background en operaciones como Sorting, Shipping, Picking e Inventory 
creo que podria ser un candidato ideal para su sucursal y aportar gran valor al equipo 
Mis Superiores ya se encuentran al tanto de esta decision y estan en la mejor dispicion de recomendar mi trabajo
de antemano muchas gracias